// <auto-generated />
namespace sport_workouts_web_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class default_exercise_img_values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(default_exercise_img_values));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111911037_default_exercise_img_values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
